algoritmo "FUNÇÕES PRÉ DEFINIDAS VISUALG"
var
   N: caractere
inicio
      Escreval("ME INFORME SEU NOME")
      Leia(N)
      Escreval("O SEU NOME TEM UM TOTAL DE", compr(N)," LETRAS")
      Escreval("O SEU NOME EM MAIÚSCULO É ", maiusc(N))
      Escreval("O SEU NOME EM MINÚSCULO É ", minusc(N))
      Escreval("A PRIMEIRA LETRA DO SEU NOME É ", copia(N, 1, 1))
      Escreval("A ÚLTIMA LETRA DO SEU NOME É ", copia(N, compr, 1))
fimalgoritmo