algoritmo "SOMA(função ou funcion"

Funcao soma(X, Y: inteiro): inteiro
Inicio
       Retorne (X + Y)
FimFuncao
var
   n1, n2, s: inteiro
inicio
      Escreval("IREMOS SOMAR 2 NÚMEROS")
      Escreva("Me informe um número: ")
      Leia(n1)
      Escreval("Me informe outro número: ")
      Leia(n2)
      s <- soma(n1, n2)
      Escreval("O valor da soma de", n1," com", n2," é igual a", s)
fimalgoritmo